version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongo-crud-app
    ports:
      - "3000:3000"
    environment:
      - USE_DOCKER=true
      - MONGO_URI=mongodb://mongo:27017/testdb
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
